### PR TITLE
Update GitOps Principles target date

### PR DESCRIPTION
**Pull request by scottrigby**
See #48

### CODE REVIEW

**Comment by lotharschulz** [comment]
LGTM

**Review by roberthstrand — APPROVED** [review]
👍🏻

**Comment by moshloop** [comment]
👎 I don't think we should be setting timelines, the initial version should be released when there is consensus on a minimum viable principles not based on an arbitrary date

**Comment by roberthstrand** [comment]
I think that setting a deadline is really helpful, if you consider concepts like Parkinson's law. If we don't reach consensus by then, we would simply have to increase meeting activity to make sure that we can discuss it further. It's not like we're going to disagree on something, but run with it due to time constraints.

**Comment by moshloop** [comment]
> simply have to increase meeting activity

This is not simple, a weekly meeting cadence is already high, multiple meetings per week is not feasible while including everyone. 

Parkinson's law might apply, but then so does #NoEstimates which is far more relevant in the software ecosystem.

If there was a physical face 2 face conference over a day or more, then you could pin it and say at the end of the conference there must be a deliverable.  

Setting an arbitrary due date based on the availability of the minority (most people part of the WG are not working full-time in the WG), is exclusionary to the majority.

**Review by bricef — APPROVED** [review]

**Comment by scottrigby** [comment]
@moshloop am I misunderstanding something about this? The end of March 2021 goal was documented since the initial GitOps Working Group announcement in [November 2020](https://github.com/gitops-working-group/gitops-working-group-old/commit/4158fd99649aa6f406dd1b4262d7f65c668045e2). Since we've passed that date, I think it's a good idea to update the timeline.

About the target date itself: we're going at a pretty good pace in these weekly sync sessions now. How about setting a new target for end of April? There's nothing saying we can't finish earlier, or change the target date again if needed.

**Comment by moshloop** [comment]
The fact that an initial date was set in November has no bearing on the progress made and the work still to be done.

To release this it needs to be finalized in the principles sync (and there still seems to be some items under contention), then presented to the WG, and finally, a PR submitted with a 14 day final consensus period with SIG App and the broader community.

Settings these dates serve no purpose other than to pressurize the release of unfinished worked. 

If there needs to be date (which I don't see why there needs to be one), set it to Q2 2021

**Comment by scottrigby** [comment]
@moshloop I'm still unclear on whether you're taking issue with the fact that a date had been set in the first place, or that I think we should update it?

To be clear, I don't think there _must_ be a date set. However there has _already_ been a date set for 5 months – at the very beginning of the WG – with no complaints so far until after the date has already passed and I'm suggesting we update it. 

This is not my hill to die on – I just changed the PR to `Date TBD`. But I would like to better understand the issue you're raising to avoid future miscommunication. Maybe we can offline it?

For now, are we good?

**Comment by scottrigby** [comment]
@moshloop OK I see your 👍 Just wanted to make sure to respect the dissenting voice here! See you on the Principles Sync today 🙂

**Pull request merged**
