### PR TITLE
feat(unsolved): add initial list of unsolved issues

### PR DESCRIPTION
**Pull request by moshloop**

### CODE REVIEW

**Comment by kfox1111** [comment]
Biggest unsolved issues I know of, is plumbing around keeping containers/packaging up to date. Bits like:
* Detecting if a new container build is essentially the same as an existing image. Don't bump version number or replace it. Stop the update pipeline without actually failing it. (some kind of fingerprint of useful files/deb/rpms but not every file. trivial /var/log differences don't require a new container)
* New version detected because of a dependency update, cut a new release of container
* Some standardized notification format for expressing there is a new version (something like rss/atom? cloudevents?)
* some way to trigger the packaging to get updated. a new helm package should be build/released, or kustomize or whatever
* Some standardized notification format/mechanism for a new chart/kustomize thingy has been released and everyone should upgrade to it. Either to do it directly, or start processing it through their own test/prod pipelines. IE, standardized way of communication between CI and CD teams.
* Some kind of plumbing to watch for notifications and push PR/MR's with the updated versions back to git. No standard api for making a MR/PR exists yet. Maybe it should be standardized. Or maybe the registration for watching can be standardized enough that it can be loaded into existing tools that do it.

Some folks assume gitops is only useful for self built software where they are deploying it themselves and developing it quickly so upgrades happen constantly driven by the dev team. But when you have CI and CD at different teams or even organizations, or the application is stable enough it only gets released relatively infrequently, (a few times a year) then dependency upgrades drive the updates rather then devs and more automation around it is necessary.

Maybe all of this is out of scope, or maybe just some. Not sure.

**Comment by moshloop** [comment]
From slack: https://cloud-native.slack.com/archives/C01G9DEE88M/p1614080202011300

**Comment by cdavisafc** [comment]
I really like the idea of having a list of unsolved things. What to folks think about doing this as a single doc. Seems like a reasonable place to start. What do others think?

**Comment by scottrigby** [comment]
These commits need DCO signoff to be merged to this repo, even temporarily https://github.com/gitops-working-group/gitops-working-group/pull/52/checks

Once this is further along, perhaps we want to add it to https://github.com/open-gitops/documents now that we have that repo?

**Comment by Oded-B** [comment]
> These commits need DCO signoff to be merged to this repo, even temporarily https://github.com/gitops-working-group/gitops-working-group/pull/52/checks
> 
> Once this is further along, perhaps we want to add it to https://github.com/open-gitops/documents now that we have that repo?

I'm assuming this isn't required for a co-author - the PR author can sign of on all the commits, right?

"The contribution was created in whole **or in part by me** and I have the right to submit it under the open source license indicated in the file"

**Comment by scottrigby** [comment]
@Oded-B Correct. PR author could edit existing commit messages and add DCO signoff, or could squash and manually ensure co-authorship attribution is correct, and that squash could have signoff.
 
Also, now that we are farther along with https://github.com/open-gitops/documents it would probably be best to open a PR there directly instead, as this is the intended place for lasting GitOps documents. The files in this repo is in the process of being split up properly between the appropriate repos under https://github.com/open-gitops, and the `gitops-wg` directory under https://github.com/cncf/tag-app-delivery.

**Comment by lloydchang** [comment]
@moshloop @Oded-B Generally re: DCO, I found the the following useful.  Thank you!

@scottrigby wrote in https://github.com/gitops-working-group/gitops-working-group/pull/117
>  just need to amend your commit to add your DCO signoff
>
> PS, you may be interested in this fun plugin I made to help with this when using the GitHub UI 😸 https://github.com/scottrigby/dco-gh-ui/
>
> I made this because this issue eventually happens to almost everyone contributing to CNCF/LF projects that require DCO.

**Comment by scottrigby** [comment]
@moshloop would you please open this in the open-gitops repo? Perhaps a discussion would be more fruitful to start? But your call. We just need to close all open PRs from this repo.
- See https://github.com/open-gitops/project/issues/2

PS this most likely would have been merged long ago as a working document if you had addressed the DCO requirement. If you do decide to open this as a PR in the open-gitops/documents repo, please make sure to add DCO signoff to each commit. Thanks!

**Pull request closed without merging**
