### PR TITLE
Finish cleaning out already moved WG repo files

### PR DESCRIPTION
**Pull request by scottrigby**
- Part of https://github.com/open-gitops/project/issues/2

## Does not include
- https://github.com/open-gitops/project/issues/26
- Linting GitHub workflow https://github.com/gitops-working-group/gitops-working-group/blob/main/.github/workflows/linter.yml

### CODE REVIEW

**Review by cdenneen — APPROVED** [review]

**Review by christianh814 — APPROVED** [review]
LGTM

**Comment by scottrigby** [comment]
Linter was giving us grief. Rather than debug it, let's just remove it before archiving the repo

**Pull request merged**
