### PR TITLE
Add GWG and OGO logo assets

### PR DESCRIPTION
**Pull request by iboonox**

### CODE REVIEW

**Comment by iboonox** [comment]
GWG logo assets added https://github.com/gitops-working-group/gitops-working-group/pull/124/commits/9211839914254f983478aba4c672bb9e384add99

**Review by scottrigby — COMMENTED** [review]
@iboonox these look fantastic IMO 🏆 

One note, the assets/logos/OGO/styleguide.svg file looks like a different typeface than Lato is used in the SVG image itself. GitHub won't allow me to make a suggested change on a binary file, but do you see what I mean?

**Comment by iboonox** [comment]
No the font used is Lato

**Review by scottrigby — APPROVED** [review]
Never mind, I get it. While the GWG styleguide is vectorized, the OGO styleguide SVG is not, and I didn't have Lato font installed. We may want to do the same for the OGO styleguide, but we can do refinements in a follow-up PR. This is 💯 🏆

**Comment by amye** [comment]
@scottrigby: does this change with the naming change as well?

**Comment by scottrigby** [comment]
@amye I believe we should be set with these designs:

- https://github.com/gitops-working-group/gitops-working-group/tree/main/assets/logos/OGO holds the logos for the Sandbox project, now renamed to "OpenGitOps". This is what I plan to add as a PR in https://github.com/cncf/artwork
- https://github.com/gitops-working-group/gitops-working-group/tree/main/assets/logos/GWG this holds a logo for the limited-time GitOps WG under SIG App Delivery. I understand working groups don't normally have logos, so this is really just for fun and I'm guessing not something CNCF would want in https://github.com/cncf/artwork

If I understood what you meant correctly

**Comment by amye** [comment]
That is what I was asking yes! As for the 2nd, having all the artwork in one place is fine, put in a PR under 'other' in /artwork

**Comment by scottrigby** [comment]
@amye OK perfect 👌 PRs made:
- https://github.com/cncf/artwork/pull/233
- https://github.com/cncf/artwork/pull/234

I'll also post in the TOC project onboarding issue

**Pull request merged**
