### PR TITLE
Add Argo into the recommendation.

### PR DESCRIPTION
**Pull request by todaywasawesome**
I had some people reach out to see if GWP was really vendor-neutral because of the endorsement on Flux. I think we either need to remove Flux or add Argo CD so we don't give the impression that the GWP is partial to a specific solution. 

Signed-off-by: Dan Garfield <dan@todaywasawesome.com>

### CODE REVIEW

**Comment by lloydchang** [comment]
@todaywasawesome @scottrigby

I understand that GitOps WG is within CNCF App Delivery TAG...

Curiously, did anyone raise any concerns _at all_ about how Argo CD and Flux CD are both CNCF and Linux Foundation projects?  What about their sibling(?), Keptn, also in CNCF and Linux Foundation?

I'm _just_ listing _some_ URLs below.

Whether they each qualify for GitOps principles, I don't know... but at least, I am bringing them up for conversation in the context of this pull request...

I understand the directive of the GitOps WG is to be principle-led and vendor-neutral... To play the devil's advocate: What if a person or team _really_ prefers having a vendor-specific GitOps... and the advantages and disadvantages that a vendor can bring?  Should they simply look elsewhere?  What is that fine-line between vendor-neutral and vendor-specific?

---

**Open Source:**

**Apache Foundation:**

Apache Liminal https://incubator.apache.org/clutch/liminal.html

**Cloud Native Computing Foundation & Linux Foundation:**

Argo CD https://argo-cd.readthedocs.io/

Flux CD https://fluxcd.io/

Keptn https://keptn.sh/

**Continuous Delivery Foundation & Linux Foundation:**

Jenkins https://www.jenkins.io/

Jenkins X https://jenkins-x.io/

Ortelius https://ortelius.io/

Screwdriver CD https://screwdriver.cd/

Spinnaker https://spinnaker.io/

Tekton https://tekton.dev/

**Repositories tagged as `gitops` in GitHub**

https://github.com/topics/gitops

---

**Open Source, Vendor-specific, presented via Open Infrastructure Foundation:**

Automium https://github.com/automium and https://www.youtube.com/watch?v=U3yNeGo1H08

I'm listing Automium here as an example because it has a corresponding presentation video titled: GitOps on OpenStack.

---

**Close Source, and Vendor-specific**

GitHub Actions https://docs.github.com/en/actions

Considering this pull request is hosted in GitHub, I should mention GitHub Actions as the obvious, closed source, and vendor-specific example... Sometimes, _just_ sometimes, people or teams _really_ do prefer using a closed source and vendor-specific system or tool for the sake of immediate practicality regardless of any directive and/or any ideals.

**Review by lloydchang — APPROVED** [review]

**Comment by scottrigby** [comment]
Hey @lloydchang this was addressed in a different way in #167, so we should close this now.

In short, I agree. The better place for this is not one or two examples in a readme, but a GitOps landscape, including all the tools that fit the principles. How to address this is TBD, but it's work set out in the GitOps WG charter. Now that the principles have a first full release, we can begin to do that other work on this foundation 😊

**Review by lloydchang — CHANGES_REQUESTED** [review]
Close this because of https://github.com/gitops-working-group/gitops-working-group/pull/166#issuecomment-939219040 and https://github.com/gitops-working-group/gitops-working-group/pull/167

**Comment by lloydchang** [comment]
@scottrigby Why would we spend time complicating `open-gitops` and duplicate `landscape`?

`landscape` already has a mechanism:
> [If you think your company or project should be included, please open a pull request to add it to landscape.yml.](https://github.com/cncf/landscape)

People can already search for `gitops` in https://github.com/cncf/landscape/blob/master/landscape.yml

**Comment by lloydchang** [comment]
@scottrigby Please review https://github.com/open-gitops/documents/pull/34 when your time permits. Thank you!

**Comment by lloydchang** [comment]
Relates to:
• https://github.com/open-gitops/documents/pull/34
• https://github.com/fluxcd/website/pull/612
• https://cloud-native.slack.com/archives/C01G9DEE88M/p1635706634045400?thread_ts=1635251844.014900

**Comment by kingdonb** [comment]
I don't personally see anything wrong with adding ArgoCD to this list, but...

I have questions about the veracity as a data source of these CNCF tech radars and its relevance for inclusion here. It isn't clear enough to me how these technologies were chosen to be sorted into buckets "Adopt", "Trial", "Assess" – it seems to be fully driven by companies that self-selected and joined their own Tech Radar teams to the End User Communities. I'm not questioning the validity of Tech Radar surveys so much as I would question its relevance here.

Also note that neither Flux nor ArgoCD are properly vendors, so an endorsement of one such tool (or more than one such tool) that best embodies GitOps principles, should not be considered threatening to any expression of vendor-neutrality.

It is up to this body to determine the objective criteria that governs which tools are, and which aren't, properly GitOps. I do not consider in-scope for GWG to pick winners and losers. But I would have more faith in the idea that certain tools can be objectively compared within the context of OpenGitOps principles and have their fitness as GitOps tools evaluated on that objective basis, better than deciding by Tech Radar or some other similar murky/subjective process.

If Keptn, Jenkins-X, or any given solution wanted to be included in this list, I would expect the decision about whether they can be called "GitOps" properly, or "Strong GitOps," etc. to be based solely on the understanding put forth by the WG; to come from within the GitOps WG itself, or community feedback that we solicit based on that particular question.

We would not wait for validation from another CNCF Tech Radar on tangentially related topics (like Continuous Delivery, or DevSecOps) nor would we defer to such sources as a basis why those tools can/cannot be included here in this list.

**Comment by scottrigby** [comment]
This has been addressed in the readme's new location: https://github.com/cncf/tag-app-delivery/blob/main/gitops-wg/README.md. Closing this issue.
- Related to https://github.com/open-gitops/project/issues/2

@lloydchang the landscape conversation is relevant. Not sure why you closed the linked issue you created – I think it is still a good issue – please feel free to reopen it. Either way we will all definitely be collaborating on that soon as part of one of the planned work products 😄

**Pull request closed without merging**
